export { Editor } from './editor/editor'
export { ProjectPage as Project } from './project/project'
export { MyTemplates } from './my-templates/my-templates'
export { MyProjects } from './my-projects/my-projects'
export { NotFound } from './not-found/not-found'
